#!/usr/bin/node

// Country list builder
var http = require('http');
var fs = require('fs');

http.get('http://data.okfn.org/data/core/country-codes/r/country-codes.json', function(res){
	res.setEncoding('utf8');
	var data="";
	res.on('data', function (chunk) { // Fill the buffer with the data
		data += chunk;
	});

	res.on('end', function(){ // When we're done receiving the data...
		data = JSON.parse(data); // Parse the JSON so we can adapt the data

		var countries_en = {}, countries_fr = {}, countries_codes = [];
		// Fill the objects
		for(var i=0; i<data.length; i++){
			try{
				fs.accessSync(__dirname + '/../static/images/flags/' + data[i]["ISO3166-1-Alpha-2"].toLowerCase() + '.svg'); // Only show countries for which we have a flag
			} catch(e) {
				console.log('Country ' + data[i].name + ' (' + data[i]["ISO3166-1-Alpha-2"].toLowerCase() + ') skipped');
				continue;
			}
			countries_codes.push(data[i]["ISO3166-1-Alpha-2"].toLowerCase());
			countries_en[data[i]["ISO3166-1-Alpha-2"].toLowerCase()] = data[i].name;
			countries_fr[data[i]["ISO3166-1-Alpha-2"].toLowerCase()] = data[i].name_fr;
		}
		console.log(i + ' countries added');
		
		//Write the files
		fs.writeFileSync('countries.js', '// This file was automatically generated by /other/country_list.js. Don\'t edit it !\n' + 'i18n("en", ' + JSON.stringify({country : countries_en}) + '); i18n("fr", ' + JSON.stringify({country : countries_fr}) + ');');
		fs.writeFileSync('country_codes', 'country_codes = ["' + countries_codes.sort().join('","') + '"];');
	});
});
